name: Test Installation

on:
  push:
    branches:
      - main

jobs:
  test_installation:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        use-mirror: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install bettyfixer

    - name: Run test script
      run: |
        # Include your specific testing commands here
        # For example, you might want to run a script that imports bettystyle and performs tests
        python your_test_script.py
